Repository RandomDataMaker/rdm-services, pull requests merged in 2020-05, with the labels that each got.

#17 Added docker-compose (web + db)
  Dockerfile
  README.md
  docker-compose.yml
  init.sh
  peselgen/settings.py
Labels: enhancement, ready to merge

#16 Data anonymization
  .gitignore
  .idea/.gitignore
  .idea/PeselGen.iml
  .idea/dataSources.xml
  .idea/encodings.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  anonymization/anonymize.py
  generator/admin.py
  metrics/migrations/0001_initial.py
  metrics/models.py
  metrics/views.py
  person/admin.py
  person/models.py
  person/person_service.py
  person/views.py
Labels: enhancement, ready to merge

#24 CircleCI configuration for PR and deployment
  .circleci/config.yml
  Dockerfile
  README.md
  docker-compose.yml
  init.sh
  peselgen/settings-dev.py
  peselgen/settings.py
Labels: enhancement, ready to merge

#27 Feature/swagger
  .gitignore
  attributes/serializer.py
  attributes/swagger.py
  attributes/urls.py
  attributes/views.py
  generator/generator.py
  generator/swagger.py
  generator/urls.py
  generator/views.py
  metrics/migrations/0001_initial.py
  metrics/migrations/__init__.py
  metrics/serializer.py
  metrics/swagger.py
  metrics/urls.py
  metrics/views.py
  person/migrations/0004_auto_20200514_0000.py
  person/serializer.py
  person/swagger.py
  person/urls.py
  person/views.py
  peselgen/settings-dev.py
  peselgen/settings.py
  peselgen/urls.py
  requirements.txt
Labels: enhancement, refactor

#28 Feature/swagger
  person/swagger.py
  peselgen/settings.py
Labels: bug
